import Link from "next/link";

const templates = [
  { name: "Make it a moment", category: "Event flyer", style: "art-orange", kicker: "SAVE THE DATE", title: "MAKE IT\nA MOMENT", copy: "Good people. Big ideas. One unforgettable night.", foot: "FRIDAY · 7 PM" },
  { name: "A little more you", category: "Personal brand", style: "art-violet", kicker: "YOUR NEXT CHAPTER", title: "A LITTLE\nMORE YOU.", copy: "Show up boldly. Your story deserves the spotlight.", foot: "START SOMETHING" },
  { name: "Good things grow", category: "Wellness", style: "art-green", kicker: "A NOTE TO SELF", title: "GOOD THINGS\nGROW SLOWLY.", copy: "Give yourself room to become.", foot: "GROW AT YOUR PACE" },
  { name: "The weekend edit", category: "Promotion", style: "art-dark", kicker: "THE WEEKEND EDIT", title: "YOUR NEXT\nFAVOURITE THING.", copy: "A small drop with a big point of view.", foot: "SHOP THE DROP" }
];

export default function HomePage() {
  return <main>
    <header className="container nav">
      <Link className="logo" href="/"><span className="logo-mark">P</span> PosterStudio</Link>
      <nav className="nav-links" aria-label="Main navigation"><Link href="/#templates">Templates</Link><Link href="/#features">Features</Link><Link href="/#pricing">Pricing</Link><Link className="btn btn-secondary" href="/editor">Open studio <span aria-hidden="true">↗</span></Link></nav>
    </header>
    <section className="hero container">
      <div className="eyebrow"><span>✳</span> A CREATIVE STUDIO FOR WHAT’S NEXT</div>
      <h1>Ideas deserve<br/>to be <span>seen.</span></h1>
      <p className="hero-copy">Create scroll-stopping content for your brand, business, or next big idea. Start with a polished layout, make it yours, and export in minutes.</p>
      <div className="hero-actions"><Link className="btn btn-primary" href="/editor">Create a design <span aria-hidden="true">→</span></Link><Link className="btn btn-secondary" href="/#templates">Explore templates</Link></div>
      <div className="preview-shell" aria-label="PosterStudio application preview">
        <div className="preview-bar"><i className="dot"/><i className="dot"/><i className="dot"/><span style={{marginLeft:10}}>Untitled design — PosterStudio</span></div>
        <div className="preview-app"><aside className="preview-side"><strong>DESIGN TOOLS</strong><div className="tool-row active">▧ Templates</div><div className="tool-row">T Text</div><div className="tool-row">◇ Elements</div><div className="tool-row">▧ Uploads</div><div className="tool-row">◐ Background</div></aside>
          <div className="preview-workspace"><div className="poster"><div className="poster-kicker">THE CREATIVE CLUB</div><h3>MAKE<br/>ROOM<br/>FOR BIG<br/>IDEAS.</h3><p>For the things you can’t stop thinking about.</p><div className="poster-shape"/><div className="poster-tag">CREATE YOUR OWN RULES</div></div></div>
          <aside className="preview-props"><strong>Design properties</strong><div className="prop-line"/><div className="prop-line short"/><div className="prop-line"/><div className="prop-line short"/><div style={{display:"flex",gap:7,marginTop:20}}><i className="dot" style={{width:20,height:20,background:"#f5c45a"}}/><i className="dot" style={{width:20,height:20,background:"#6941f4"}}/><i className="dot" style={{width:20,height:20,background:"#252a42"}}/></div></aside>
        </div>
      </div>
    </section>
    <section className="section container" id="templates"><div className="section-head"><div className="eyebrow">A HEAD START, NOT A SHORTCUT</div><h2>Start strong. Make it yours.</h2><p>A considered collection of starting points for brands, creators, and teams.</p></div>
      <div className="template-grid">{templates.map((item) => <Link className="template-card" href="/editor" key={item.name}><div className={"template-art "+item.style}><small>{item.kicker}</small><div><h3>{item.title.split("\n").map((line,i)=><span key={line+i} style={{display:"block",letterSpacing:"-1px"}}>{line}</span>)}</h3><p>{item.copy}</p></div><span>{item.foot}</span><div className="art-orb"/></div><div style={{padding:"14px 15px"}}><strong style={{fontSize:13}}>{item.name}</strong><p style={{margin:"5px 0 0",fontSize:12,color:"#858190"}}>{item.category}</p></div></Link>)}</div>
      <div style={{textAlign:"center",marginTop:28}}><Link className="btn btn-secondary" href="/editor">Explore the studio →</Link></div>
    </section>
    <section className="section" id="features" style={{background:"#f4f2f9"}}><div className="container"><div className="section-head"><div className="eyebrow">YOUR CREATIVE SPACE</div><h2>Powerful tools.<br/>A clearer creative flow.</h2><p>The essentials to move from rough idea to finished visual without the clutter.</p></div>
      <div className="feature-grid"><article className="feature"><div className="feature-icon">▧</div><h3>Start with a spark</h3><p>Use a template or begin with a blank canvas sized for your favourite social platform.</p></article><article className="feature"><div className="feature-icon">✳</div><h3>Make every detail yours</h3><p>Edit text, colour, shapes and imagery in a hands-on canvas built for quick iteration.</p></article><article className="feature"><div className="feature-icon">↗</div><h3>Ready for the feed</h3><p>Export your finished artwork as a crisp PNG or JPEG, sized to your design.</p></article></div>
    </div></section>
    <section className="section container" id="pricing"><div className="section-head"><div className="eyebrow">SIMPLE BY DESIGN</div><h2>Room to create at every stage.</h2><p>Start free. Upgrade when your creative work calls for more.</p></div><div className="pricing-grid"><article className="price-card"><h3>Free</h3><p>For your first big idea.</p><div className="price">$0 <span style={{fontSize:13,fontWeight:400,letterSpacing:0}}>/ forever</span></div><ul><li>Core canvas editor</li><li>PNG and JPEG export</li><li>Browser-based draft saving</li></ul><Link className="btn btn-secondary" href="/editor" style={{width:"100%"}}>Start creating</Link></article><article className="price-card popular"><div className="eyebrow">COMING INTO FOCUS</div><h3 style={{marginTop:14}}>Pro</h3><p>For your everyday creative work.</p><div className="price">$12 <span style={{fontSize:13,fontWeight:400,letterSpacing:0}}>/ month</span></div><ul><li>Planned premium templates</li><li>Brand kits and shared assets</li><li>Higher export limits</li></ul><a className="btn btn-primary" href="mailto:hello@posterstudio.example?subject=PosterStudio%20Pro" style={{width:"100%"}}>Join the waitlist</a></article><article className="price-card"><h3>Team</h3><p>For brands making things together.</p><div className="price">Let’s talk</div><ul><li>Planned team workspaces</li><li>Brand consistency tools</li><li>Team collaboration</li></ul><a className="btn btn-secondary" href="mailto:hello@posterstudio.example?subject=PosterStudio%20Teams" style={{width:"100%"}}>Contact us</a></article></div><p style={{textAlign:"center",fontSize:12,color:"#858190",marginTop:18}}>Pro and Team are preview plans; payment is not enabled.</p></section>
    <section className="section" style={{background:"#f4f2f9"}}><div className="container"><div className="section-head"><div className="eyebrow">GOOD QUESTIONS</div><h2>Before you get creating.</h2></div><div className="faq"><details><summary>Do I need design experience?</summary><p>Not at all. Start with a blank canvas or use the editor’s sample layouts and simple tools to build your own poster.</p></details><details><summary>Can I download my design?</summary><p>Yes. The editor supports exporting the current canvas as PNG or JPEG at its configured dimensions.</p></details><details><summary>Are my designs stored in the cloud?</summary><p>You can work with local drafts or sign in to save supported projects to your private cloud workspace.</p></details><details><summary>Can I use it on my phone?</summary><p>The landing page and basic editor controls adapt to smaller screens. For detailed canvas work, a desktop or tablet is recommended.</p></details></div></div></section>
    <footer className="footer"><div className="container footer-inner"><Link className="logo" href="/"><span className="logo-mark">P</span> posterstudio</Link><span>Make something worth stopping for.</span><span>© {new Date().getFullYear()} PosterStudio · <Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>
  </main>;
}
